export default {
    GET_ALL_COURSES: 'GET_ALL_COURSES',

    GET_ALL_COURSES_REQUEST: 'GET_ALL_COURSES_REQUEST',
    GET_ALL_COURSES_RESPONSE: 'GET_ALL_COURSES_RESPONSE',
    GET_ALL_COURSES_ERROR: 'GET_ALL_COURSES_ERROR',

    GET_COURSE_BY_ID: 'GET_COURSE_BY_ID',

    GET_COURSE_BY_ID_REQUEST: 'GET_COURSE_BY_ID_REQUEST',
    GET_COURSE_BY_ID_RESPONSE: 'GET_COURSE_BY_ID_RESPONSE',
    GET_COURSE_BY_ID_ERROR: 'GET_COURSE_BY_ID_ERROR',

    ADD_COURSE: 'ADD_COURSE',

    ADD_COURSE_REQUEST: 'ADD_COURSE_REQUEST',
    ADD_COURSE_RESPONSE: 'ADD_COURSE_RESPONSE',
    ADD_COURSE_ERROR: 'ADD_COURSE_ERROR',

    UPDATE_COURSE: 'UPDATE_COURSE',

    UPDATE_COURSE_REQUEST: 'UPDATE_COURSE_REQUEST',
    UPDATE_COURSE_RESPONSE: 'UPDATE_COURSE_RESPONSE',
    UPDATE_COURSE_ERROR: 'UPDATE_COURSE_ERROR',

    GET_SOFTWARE: 'GET_SOFTWARE',

    GET_SOFTWARE_REQUEST: 'GET_SOFTWARE_REQUEST',
    GET_SOFTWARE_RESPONSE: 'GET_SOFTWARE_RESPONSE',
    GET_SOFTWARE_ERROR: 'GET_SOFTWARE_ERROR',

    ADD_SOFTWARE: 'ADD_SOFTWARE',

    ADD_SOFTWARE_REQUEST: 'ADD_SOFTWARE_REQUEST',
    ADD_SOFTWARE_RESPONSE: 'ADD_SOFTWARE_RESPONSE',
    ADD_SOFTWARE_ERROR: 'ADD_SOFTWARE_ERROR',

    UPDATE_SOFTWARE: 'UPDATE_SOFTWARE',

    UPDATE_SOFTWARE_REQUEST: 'GET_SOFTWARE_REQUEST',
    UPDATE_SOFTWARE_RESPONSE: 'GET_SOFTWARE_RESPONSE',
    UPDATE_SOFTWARE_ERROR: 'GET_SOFTWARE_ERROR',

    GET_USER_BY_ID: 'GET_USER_BY_ID',

    GET_USER_BY_ID_REQUEST: 'GET_USER_BY_ID_REQUEST',
    GET_USER_BY_ID_RESPONSE: 'GET_USER_BY_ID_RESPONSE',
    GET_USER_BY_ID_ERROR: 'GET_USER_BY_ID_ERROR',

    UPDATE_USER: 'UPDATE_USER',

    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_RESPONSE: 'UPDATE_USER_RESPONSE',
    UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',

    GET_CURRENT_USER: 'GET_CURRENT_USER',

    GET_CURRENT_USER_REQUEST: 'GET_CURRENT_USER_REQUEST',
    GET_CURRENT_USER_RESPONSE: 'GET_CURRENT_USER_RESPONSE',
    GET_CURRENT_USER_ERROR: 'GET_CURRENT_USER_ERROR',

    SEND_REVIEW: 'SEND_REVIEW',

    SEND_REVIEW_REQUEST: 'SEND_REVIEW_REQUEST',
    SEND_REVIEW_RESPONSE: 'SEND_REVIEW_RESPONSE',
    SEND_REVIEW_ERROR: 'SEND_REVIEW_ERROR',

    GET_ALL_REVIEWS: 'GET_ALL_REVIEWS',

    GET_ALL_REVIEWS_REQUEST: 'GET_ALL_REVIEWS_REQUEST',
    GET_ALL_REVIEWS_RESPONSE: 'GET_ALL_REVIEWS_RESPONSE',
    GET_ALL_REVIEWS_ERROR: 'GET_ALL_REVIEWS_ERROR',

    UPDATE_REVIEW: 'UPDATE_REVIEW',

    UPDATE_REVIEW_REQUEST: 'UPDATE_REVIEW_REQUEST',
    UPDATE_REVIEW_RESPONSE: 'UPDATE_REVIEW_RESPONSE',
    UPDATE_REVIEW_ERROR: 'UPDATE_REVIEW_ERROR',

    DELETE_REVIEW: 'DELETE_REVIEW',

    DELETE_REVIEW_REQUEST: 'DELETE_REVIEW_REQUEST',
    DELETE_REVIEW_RESPONSE: 'DELETE_REVIEW_RESPONSE',
    DELETE_REVIEW_ERROR: 'DELETE_REVIEW_ERROR',

    CREATE_STUDIED_COURSE: 'CREATE_STUDIED_COURSE',

    CREATE_STUDIED_COURSE_REQUEST: 'CREATE_STUDIED_COURSE_REQUEST',
    CREATE_STUDIED_COURSE_RESPONSE: 'CREATE_STUDIED_COURSE_RESPONSE',
    CREATE_STUDIED_COURSE_ERROR: 'CREATE_STUDIED_COURSE_ERROR',

    UPDATE_STUDIED_COURSE: 'UPDATE_STUDIED_COURSE',

    UPDATE_STUDIED_COURSE_REQUEST: 'UPDATE_STUDIED_COURSE_REQUEST',
    UPDATE_STUDIED_COURSE_RESPONSE: 'UPDATE_STUDIED_COURSE_RESPONSE',
    UPDATE_STUDIED_COURSE_ERROR: 'UPDATE_STUDIED_COURSE_ERROR',

    DELETE_STUDIED_COURSE: 'DELETE_STUDIED_COURSE',

    DELETE_STUDIED_COURSE_REQUEST: 'DELETE_STUDIED_COURSE_REQUEST',
    DELETE_STUDIED_COURSE_RESPONSE: 'DELETE_STUDIED_COURSE_RESPONSE',
    DELETE_STUDIED_COURSE_ERROR: 'DELETE_STUDIED_COURSE_ERROR',

    GET_CHAT_MESSAGES: 'GET_CHAT_MESSAGES',

    GET_CHAT_MESSAGES_REQUEST: 'GET_CHAT_MESSAGES_REQUEST',
    GET_CHAT_MESSAGES_RESPONSE: 'GET_CHAT_MESSAGES_RESPONSE',
    GET_CHAT_MESSAGES_ERROR: 'GET_CHAT_MESSAGES_ERROR',

    SEND_CHAT_MESSAGE: 'SEND_CHAT_MESSAGE',

    SEND_CHAT_MESSAGE_REQUEST: 'SEND_CHAT_MESSAGE_REQUEST',
    SEND_CHAT_MESSAGE_RESPONSE: 'SEND_CHAT_MESSAGE_RESPONSE',
    SEND_CHAT_MESSAGE_ERROR: 'SEND_CHAT_MESSAGE_ERROR',

    GET_PRIVATE_MESSAGES: 'GET_PRIVATE_MESSAGES',

    GET_PRIVATE_MESSAGES_REQUEST: 'GET_PRIVATE_MESSAGES_REQUEST',
    GET_PRIVATE_MESSAGES_RESPONSE: 'GET_PRIVATE_MESSAGES_RESPONSE',
    GET_PRIVATE_MESSAGES_ERROR: 'GET_PRIVATE_MESSAGES_ERROR',

    SEND_PRIVATE_MESSAGE: 'SEND_PRIVATE_MESSAGE',

    SEND_PRIVATE_MESSAGE_REQUEST: 'SEND_PRIVATE_MESSAGE_REQUEST',
    SEND_PRIVATE_MESSAGE_RESPONSE: 'SEND_PRIVATE_MESSAGE_RESPONSE',
    SEND_PRIVATE_MESSAGE_ERROR: 'SEND_PRIVATE_MESSAGE_ERROR',

    UPDATE_PRIVATE_MESSAGE: 'UPDATE_PRIVATE_MESSAGE',

    UPDATE_PRIVATE_MESSAGE_REQUEST: 'UPDATE_PRIVATE_MESSAGE_REQUEST',
    UPDATE_PRIVATE_MESSAGE_RESPONSE: 'UPDATE_PRIVATE_MESSAGE_RESPONSE',
    UPDATE_PRIVATE_MESSAGE_ERROR: 'UPDATE_PRIVATE_MESSAGE_ERROR',

    GET_ALL_USERS: 'GET_ALL_USERS',

    GET_ALL_USERS_REQUEST: 'GET_ALL_USERS_REQUEST',
    GET_ALL_USERS_RESPONSE: 'GET_ALL_USERS_RESPONSE',
    GET_ALL_USERS_ERROR: 'GET_ALL_USERS_ERROR',

    GET_ALL_POSTS: 'GET_ALL_POSTS',

    GET_ALL_POSTS_REQUEST: 'GET_ALL_POSTS_REQUEST',
    GET_ALL_POSTS_RESPONSE: 'GET_ALL_POSTS_RESPONSE',
    GET_ALL_POSTS_ERROR: 'GET_ALL_POSTS_ERROR',

    GET_POST_BY_ID: 'GET_POST_BY_ID',

    GET_POST_BY_ID_REQUEST: 'GET_POST_BY_ID_REQUEST',
    GET_POST_BY_ID_RESPONSE: 'GET_POST_BY_ID_RESPONSE',
    GET_POST_BY_ID_ERROR: 'GET_POST_BY_ID_ERROR',

    ADD_POST: 'ADD_POST',

    ADD_POST_REQUEST: 'ADD_POST_REQUEST',
    ADD_POST_RESPONSE: 'ADD_POST_RESPONSE',
    ADD_POST_ERROR: 'ADD_POST_ERROR',

    UPDATE_POST: 'UPDATE_POST',

    UPDATE_POST_REQUEST: 'UPDATE_POST_REQUEST',
    UPDATE_POST_RESPONSE: 'UPDATE_POST_RESPONSE',
    UPDATE_POST_ERROR: 'UPDATE_POST_ERROR',

    DELETE_POST: 'DELETE_POST',

    DELETE_POST_REQUEST: 'DELETE_POST_REQUEST',
    DELETE_POST_RESPONSE: 'DELETE_POST_RESPONSE',
    DELETE_POST_ERROR: 'DELETE_POST_ERROR',

    LIKE_POST: 'LIKE_POST',

    LIKE_POST_REQUEST: 'LIKE_POST_REQUEST',
    LIKE_POST_RESPONSE: 'LIKE_POST_RESPONSE',
    LIKE_POST_ERROR: 'LIKE_POST_ERROR',

    DISLIKE_POST: 'DISLIKE_POST',

    DISLIKE_POST_REQUEST: 'DISLIKE_POST_REQUEST',
    DISLIKE_POST_RESPONSE: 'DISLIKE_POST_RESPONSE',
    DISLIKE_POST_ERROR: 'DISLIKE_POST_ERROR',

    GET_ALL_COMMENTS: 'GET_ALL_COMMENTS',

    GET_ALL_COMMENTS_REQUEST: 'GET_ALL_COMMENTS_REQUEST',
    GET_ALL_COMMENTS_RESPONSE: 'GET_ALL_COMMENTS_RESPONSE',
    GET_ALL_COMMENTS_ERROR: 'GET_ALL_COMMENTS_ERROR',

    GET_COMMENTS_BY_POST_ID: 'GET_COMMENTS_BY_POST_ID',

    GET_COMMENTS_BY_POST_ID_REQUEST: 'GET_COMMENTS_BY_POST_ID_REQUEST',
    GET_COMMENTS_BY_POST_ID_RESPONSE: 'GET_COMMENTS_BY_POST_ID_RESPONSE',
    GET_COMMENTS_BY_POST_ID_ERROR: 'GET_COMMENTS_BY_POST_ID_ERROR',

    ADD_COMMENT: 'ADD_COMMENT',

    ADD_COMMENT_REQUEST: 'ADD_COMMENT_REQUEST',
    ADD_COMMENT_RESPONSE: 'ADD_COMMENT_RESPONSE',
    ADD_COMMENT_ERROR: 'ADD_COMMENT_ERROR',

    UPDATE_COMMENT: 'UPDATE_COMMENT',

    UPDATE_COMMENT_REQUEST: 'UPDATE_COMMENT_REQUEST',
    UPDATE_COMMENT_RESPONSE: 'UPDATE_COMMENT_RESPONSE',
    UPDATE_COMMENT_ERROR: 'UPDATE_COMMENT_ERROR',

    DELETE_COMMENT: 'DELETE_COMMENT',

    DELETE_COMMENT_REQUEST: 'DELETE_COMMENT_REQUEST',
    DELETE_COMMENT_RESPONSE: 'DELETE_COMMENT_RESPONSE',
    DELETE_COMMENT_ERROR: 'DELETE_COMMENT_ERROR',

    GET_ADMIN_INITIAL: 'GET_ADMIN_INITIAL',

    GET_ADMIN_INITIAL_REQUEST: 'GET_ADMIN_INITIAL_REQUEST',
    GET_ADMIN_INITIAL_RESPONSE: 'GET_ADMIN_INITIAL_RESPONSE',
    GET_ADMIN_INITIAL_ERROR: 'GET_ADMIN_INITIAL_ERROR',

    GET_ALL_ROLES: 'GET_ALL_ROLES',

    GET_ALL_ROLES_REQUEST: 'GET_ALL_ROLES_REQUEST',
    GET_ALL_ROLES_RESPONSE: 'GET_ALL_ROLES_RESPONSE',
    GET_ALL_ROLES_ERROR: 'GET_ALL_ROLES_ERROR',

    UPDATE_ROLE: 'UPDATE_ROLE',

    UPDATE_ROLE_REQUEST: 'UPDATE_ROLE_REQUEST',
    UPDATE_ROLE_RESPONSE: 'UPDATE_ROLE_RESPONSE',
    UPDATE_ROLE_ERROR: 'UPDATE_ROLE_ERROR',

    ADD_ROLE: 'ADD_ROLE',

    ADD_ROLE_REQUEST: 'ADD_ROLE_REQUEST',
    ADD_ROLE_RESPONSE: 'ADD_ROLE_RESPONSE',
    ADD_ROLE_ERROR: 'ADD_ROLE_ERROR',

    GET_ALL_USERS_LEVELS: 'GET_ALL_USERS_LEVELS',

    GET_ALL_USERS_LEVELS_REQUEST: 'GET_ALL_USERS_LEVELS_REQUEST',
    GET_ALL_USERS_LEVELS_RESPONSE: 'GET_ALL_USERS_LEVELS_RESPONSE',
    GET_ALL_USERS_LEVELS_ERROR: 'GET_ALL_USERS_LEVELS_ERROR',

    UPDATE_USER_LEVEL: 'UPDATE_USER_LEVEL',

    UPDATE_USER_LEVEL_REQUEST: 'UPDATE_USER_LEVEL_REQUEST',
    UPDATE_USER_LEVEL_RESPONSE: 'UPDATE_USER_LEVEL_RESPONSE',
    UPDATE_USER_LEVEL_ERROR: 'UPDATE_USER_LEVEL_ERROR',

    ADD_USER_LEVEL: 'ADD_USER_LEVEL',

    ADD_USER_LEVEL_REQUEST: 'ADD_USER_LEVEL_REQUEST',
    ADD_USER_LEVEL_RESPONSE: 'ADD_USER_LEVEL_RESPONSE',
    ADD_USER_LEVEL_ERROR: 'ADD_USER_LEVEL_ERROR',

    GET_ALL_COURSES_LEVELS: 'GET_ALL_COURSES_LEVELS',

    GET_ALL_COURSES_LEVELS_REQUEST: 'GET_ALL_COURSES_LEVELS_REQUEST',
    GET_ALL_COURSES_LEVELS_RESPONSE: 'GET_ALL_COURSES_LEVELS_RESPONSE',
    GET_ALL_COURSES_LEVELS_ERROR: 'GET_ALL_COURSES_LEVELS_ERROR',

    UPDATE_COURSE_LEVEL: 'UPDATE_COURSE_LEVEL',

    UPDATE_COURSE_LEVEL_REQUEST: 'UPDATE_COURSE_LEVEL_REQUEST',
    UPDATE_COURSE_LEVEL_RESPONSE: 'UPDATE_COURSE_LEVEL_RESPONSE',
    UPDATE_COURSE_LEVEL_ERROR: 'UPDATE_COURSE_LEVEL_ERROR',

    ADD_COURSE_LEVEL: 'ADD_COURSE_LEVEL',

    ADD_COURSE_LEVEL_REQUEST: 'ADD_COURSE_LEVEL_REQUEST',
    ADD_COURSE_LEVEL_RESPONSE: 'ADD_COURSE_LEVEL_RESPONSE',
    ADD_COURSE_LEVEL_ERROR: 'ADD_COURSE_LEVEL_ERROR',

    GET_POSTS_TYPES: 'GET_POSTS_TYPES',

    GET_POSTS_TYPES_REQUEST: 'GET_POSTS_TYPES_REQUEST',
    GET_POSTS_TYPES_RESPONSE: 'GET_POSTS_TYPES_RESPONSE',
    GET_POSTS_TYPES_ERROR: 'GET_POSTS_TYPES_ERROR',

    UPDATE_POST_TYPE: 'UPDATE_POST_TYPE',

    UPDATE_POST_TYPE_REQUEST: 'UPDATE_POST_TYPE_REQUEST',
    UPDATE_POST_TYPE_RESPONSE: 'UPDATE_POST_TYPE_RESPONSE',
    UPDATE_POST_TYPE_ERROR: 'UPDATE_POST_TYPE_ERROR',

}
